apiVersion: apps/v1
kind: Deployment
metadata:
  name: cotacao
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cotacao
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: cotacao
    spec:
      containers:
      - name: cotacao
        image: rangelcr/api_cotacao:v3
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cotacao
spec:
  selector:
    app: cotacao
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30000
