apiVersion: apps/v1
kind: Deployment
metadata:
  name: cotacao
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: cotacao
  template:
    metadata:
      labels:
        app: cotacao
    spec:
      containers:
        - name: cotacao-web
          image: rangelcr/web_cotacao:latest
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              memory: "32Mi"   
              cpu: "50m"      
            limits:
              memory: "128Mi"  
              cpu: "200m" 
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cotacao-service
spec:
  selector:
    app: cotacao
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
