name: Deploy
on:
  workflow_call:
    inputs:
      manifests:
        type: string
        required: true
        description: "Arquivo de manifesto"
      images:
        type: string
        required: true
        description: "Imagens docker"

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código
        uses: actions/checkout@v4.2.2    

      - name: Configurando credenciais da aws
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Atualizando kubeconfig para EKS
        run: aws eks update-kubeconfig --name cluster-cotacao

      - name: Aplicando manifesto
        uses: Azure/k8s-deploy@v5
        with:
          manifests: ${{ inputs.manifests }}
          images: ${{ inputs.images }}

